[package]
name = "rust-http-test-server"
version = "0.1.0"
authors = ["Nandan Joshi <nandan@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
